Hw test ng
EugeneSavchits/Lesson_6 pull request #5
Opened 2022-01-10 15:58 UTC by EugeneSavchits

2022-01-17 12:08 UTC, wildpioneer commented
В проект добавлены файлы из папки target - этого делать нельзя

2022-01-17 12:08 UTC, wildpioneer requested changes

2022-01-17 12:08 UTC, wildpioneer commented on src/test/java/CalcTestDivision.java
> +        System.out.println(6/0);;
Почему ты проверяешь 6/0 вместо вызова метода

2022-01-22 01:18 UTC, EugeneSavchits commented on src/test/java/CalcTestDivision.java
> +        System.out.println(6/0);;
При вызове метода не выдает ошибку) А без метода выдает

2022-01-31 11:31 UTC, closed without merging