Hw value of objects
EugeneSavchits/Lesson_6 pull request #6
Opened 2022-01-16 22:44 UTC by EugeneSavchits

2022-01-17 12:29 UTC, wildpioneer requested changes

2022-01-17 12:29 UTC, wildpioneer commented on src/test/java/models/Project.java
> +
Кроме имени в сущности проект ничего нет?

2022-01-17 12:29 UTC, wildpioneer commented on src/test/java/pages/AddProjectPage.java
> +        String inputChars= "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
Метод рандомизации являетс вспомогательным, поэтому должен быть вынесен

2022-01-17 12:29 UTC, wildpioneer commented on src/test/java/tests/SmokeTest.java
> +
Не установлена последовательность запуска тестов, поэтому тест на удаление падает

2022-01-17 12:29 UTC, wildpioneer commented on src/test/java/tests/SmokeTest.java
> +        driver.findElement(By.xpath("//*[. = '"+project.getNameProject()+"']")).click();
Эти метода надо вынести в соответствующие страницы

2022-01-17 12:29 UTC, wildpioneer commented on src/test/java/tests/SmokeTest.java
> +        driver.findElement(By.id("navigation-admin")).click();
Какая-то смесь начальных уроков и PageObject - мне не понятно что здесь происходит

2022-01-22 01:16 UTC, EugeneSavchits commented on src/test/java/tests/SmokeTest.java
> +        driver.findElement(By.id("navigation-admin")).click();
Переделал и отправил HW2_ValueOfObject

2022-01-22 01:16 UTC, EugeneSavchits commented on src/test/java/tests/SmokeTest.java
> +        driver.findElement(By.xpath("//*[. = '"+project.getNameProject()+"']")).click();
Переделал и отправил HW2_ValueOfObject

2022-01-22 01:16 UTC, EugeneSavchits commented on src/test/java/tests/SmokeTest.java
> +
Переделал и отправил HW2_ValueOfObject

2022-01-22 01:16 UTC, EugeneSavchits commented on src/test/java/pages/AddProjectPage.java
> +        String inputChars= "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
Переделал и отправил HW2_ValueOfObject

2022-01-22 01:16 UTC, EugeneSavchits commented on src/test/java/models/Project.java
> +
Переделал и отправил HW2_ValueOfObject

2022-01-31 11:31 UTC, wildpioneer commented
Проверено

2022-01-31 11:31 UTC, closed without merging